export const FORM_ACTION = {
  SAGA: {
    LOAD_FORM_DATA: 'LOAD_FORM_DATA',
    UNLOAD_FORM_DATA: 'UNLOAD_FORM_DATA',
    UPDATE_FIELD_PROPERTY_VALUE: 'SAGA_UPDATE_FIELD_PROPERTY_VALUE',
    UPDATE_DRAFT_FIELD_PROPERTY_VALUE: 'SAGA_UPDATE_DRAFT_FIELD_PROPERTY_VALUE',
    SUBMIT_FORM_DATA: 'SUBMIT_FORM_DATA',
    SUBMIT_DRAFT_FORM_DATA: 'SUBMIT_DRAFT_FORM_DATA',
    UPLOAD_FILE: 'UPLOAD_FILE',
    UPLOAD_DRAFT_FILE: 'UPLOAD_DRAFT_FILE',
    LOAD_HISTORY_DATA: 'LOAD_HISTORY_DATA',
  },
  REDUCER: {
    SAVE_FORM_DATA: 'SAVE_FORM_DATA',
    LOAD_FORM_FIELDS: 'LOAD_FORM_FIELDS',
    REMOVE_FORM_DATA: 'REMOVE_FORM_DATA',
    UNLOAD_FORM_FIELDS: 'UNLOAD_FORM_FIELDS',
    UPDATE_FIELD_PROPERTY_VALUE: 'REDUCER_UPDATE_FIELD_PROPERTY_VALUE',
    UPDATE_DRAFT_FIELD_PROPERTY_VALUE: 'REDUCER_UPDATE_DRAFT_FIELD_PROPERTY_VALUE',
    UPDATE_SCROLL_TO_REQUIRED: 'UPDATE_SCROLL_TO_REQUIRED',
    SAVE_HISTORY_DATA: 'SAVE_HISTORY_DATA',
  },
};
