export enum Screens {
  INITIAL_SCREEN = 'InitialScreen',
  AUTHENTICATION_SCREEN = 'AuthenticationScreen',
  LOGIN_SCREEN = 'LoginScreen',
  REGISTER_SCREEN = 'RegisterScreen',
  MAIN_SCREEN = 'MainScreen',
  ACTIVITY_INDICATOR_OVERLAY_SCREEN = 'ActivityIndicatorOverlay',
  HEADER_SCREEN = 'HeaderScreen',
  HOME_SCREEN = 'HomeScreen',
  HISTORY_SCREEN = 'HistoryScreen',
  NOTIFICATIONS_SCREEN = 'NotificationsScreen',
  FORMS_SCREEN = 'FormsScreen',
  FORM_FIELDS_SCREEN = 'FormFieldsScreen',
  RESULT_SCREEN = 'ResultScreen',
  PROFILE_SCREEN = 'ProfileScreen',
  FILLEDUP_FORM_FIELDS_SCREEN = 'FilledUpFormFieldsScreen',
  DRAFT_FORM_FIELDS_SCREEN = 'DraftFormFieldsScreen',
}
